version: '3.7'
services:
  postgres:
    image: postgres:12.6-alpine
    ports:
      - '5432:5432'
    volumes:
    - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=app
      - POSTGRES_DB=app

